---
platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }

inputs:
  - name: resource-tutorial
 
outputs:
  - name: updated-gist

run:
  path: resource-tutorial/docker/getversion.sh